### ISSUE TITLE
Prepare the roadmap for the engine

### ISSUE THREAD

**Issue by jeanbapti06** [jeanbapti06/LudusGameEngine#7]
Prepare :
- [x] The milestones of the engine.
- [x] What is expected within each milestone.
- [x] All the features of the engine.
- [x] When each of said features are expected to be implemented.
